micronaut:
  application:
    name: namingStrategyDemo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/namingStrategyDemo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
